/**
 * streaming-telemetry — Fire-and-forget observability for chat reliability.
 *
 * The point of this module is to *prove* which failure modes users actually
 * hit. Without it, "mensagem não apareceu" is a complaint, not a bug report.
 *
 * Design rules:
 *   1. Never block the UI on telemetry. Every emit is best-effort.
 *   2. Never throw. Telemetry must not crash the calling code path.
 *   3. Stable event names. Once emitted, names are part of the contract; treat
 *      renames like a database column rename.
 *   4. Minimal payload. Telemetry writes are O(N users × events per run). A
 *      10KB payload × 1000 users × 50 events is real Supabase cost.
 *
 * Stable event names (canonical list — add to it, never edit history):
 *   - chat.user_message_inserted     (server) — INSERT completed
 *   - chat.user_message_rendered     (client) — UI painted the bubble
 *   - agent.run_started              (server) — agent-run edge started
 *   - agent.run_first_byte           (server) — first LLM token
 *   - agent.run_dispatch_failed      (server) — Inngest event send failed
 *   - agent.stream_seq_gap           (both)   — observed non-contiguous seq
 *   - agent.stream_seq_dropped       (client) — row.seq <= lastSeqRef (dedup)
 *   - agent.stream_seq_processed     (client) — row applied (sampled 1/N)
 *   - agent.realtime_channel_error   (client) — CHANNEL_ERROR/TIMED_OUT
 *   - agent.realtime_reconnect       (client) — backoff attempt scheduled
 *   - agent.realtime_reconnected     (client) — SUBSCRIBED after reconnect
 *   - agent.snapshot_restored        (client) — F5 restore succeeded
 *   - agent.snapshot_too_stale       (client) — F5 restore cleared (>30min)
 *   - agent.materialized_shape_mismatch (client) — cardSnapshot invalid
 *   - agent.materialized_release_pending (client) — slot held > 30s
 *   - agent.plan_source_runid_missing  (client) — inspector Plan tab empty
 *   - agent.narration_stream_overlap   (client) — narration/stream overlap detected
 *   - agent.stale_stream_detected      (client) — silence > 15min (5min w/ queue)
 *   - agent.dual_tab_detected          (client) — 2nd tab took over
 */

import { supabase } from "@/integrations/supabase/client";

export type StreamingTelemetryEventName =
  | "chat.user_message_inserted"
  | "chat.user_message_rendered"
  | "agent.run_started"
  | "agent.run_first_byte"
  | "agent.run_dispatch_failed"
  | "agent.stream_seq_gap"
  | "agent.stream_seq_dropped"
  | "agent.stream_seq_processed"
  | "agent.realtime_channel_error"
  | "agent.realtime_reconnect"
  | "agent.realtime_reconnected"
  | "agent.snapshot_restored"
  | "agent.snapshot_too_stale"
  | "agent.materialized_shape_mismatch"
  | "agent.materialized_release_pending"
  | "agent.plan_source_runid_missing"
  | "agent.narration_stream_overlap"
  | "agent.stale_stream_detected"
  | "agent.dual_tab_detected";

type EmitContext = {
  projectId: string;
  runId?: string | null;
};

let currentContext: EmitContext | null = null;

export function setStreamingTelemetryContext(ctx: EmitContext | null) {
  currentContext = ctx;
}

let sampledCount = 0;
const SAMPLE_PROCESSED_DIVISOR = 10;

export function emitStreamingTelemetry(
  eventName: StreamingTelemetryEventName,
  payload: Record<string, unknown> = {},
): void {
  if (!currentContext?.projectId) return;
  if (eventName === "agent.stream_seq_processed") {
    sampledCount += 1;
    if (sampledCount % SAMPLE_PROCESSED_DIVISOR !== 0) return;
  }
  // Fire-and-forget. We do not await; we do not retry; we do not surface
  // errors. If telemetry writes are slow, the calling code path is not.
  // We cast to `any` because the generated `Database` type in
  // `src/integrations/supabase/types.ts` is regenerated by `supabase gen types`
  // and the new `agent_streaming_telemetry` table is not yet in the type
  // definition. Once regenerated, the cast can be removed.
  void (supabase
    .from("agent_streaming_telemetry" as never) as any)
    .insert({
      project_id: currentContext.projectId,
      run_id: currentContext.runId ?? null,
      event_name: eventName,
      payload,
    })
    .then(({ error }: { error: { message: string } | null }) => {
      if (error && import.meta.env.DEV) {
        // eslint-disable-next-line no-console
        console.warn("[streaming-telemetry] insert failed:", eventName, error.message);
      }
    });
}
