// AUTO-GENERATED by scripts/sync-agent-contract.mjs — do not edit.
// @forge/agent-contract — Contrato canônico de operação do agente (cooperative | HOTL).
//
// SSOT: packages/agent-contract/src/operation.ts
// SYNC: npm run sync:agent-contract → supabase/functions/_shared/agent-contract-operation.ts
// FRONTEND: src/lib/agent-operation-contract.ts re-exporta este pacote.
//
// Lei única:
// - Preferência do usuário: profiles.agent_preferences.operation (writer: UI)
// - Snapshot imutável da run: agent_runs.meta.operation (writer: Edge no dispatch start)
// - Loop só lê meta.operation — nunca reconsulta preferences no meio.

/** Padrão operativo — 60 min, fusíveis internos, Continuar só emergência. */
export type CooperativeMode = "cooperative";

/** Human on the Loop — toggle antes/durante; wall longo; report obrigatório no chat ao sair. */
export type HotlMode = "hotl";

export type OperationMode = CooperativeMode | HotlMode;

export type HotlWallHours = 24 | 48 | 72;

/** Preferência gravada em profiles.agent_preferences.operation */
export type OperationPreferences = {
  mode: OperationMode;
  /** Somente quando mode === "hotl". Default 24h se omitido. */
  hotlWallHours?: HotlWallHours;
};

/** Meta gravado em agent_runs.meta.operation (e design_dna_jobs.meta.operation). */
export type RunOperationMeta = {
  mode: OperationMode;
  /** ISO-8601 — início da operação (mesmo runId, mesmo worker). */
  startedAt: string;
  /** Teto da operação em ms (cooperative 60min ou HOTL 24/48/72h). */
  wallMs: number;
  /** HOTL: report no chat em exit normal, erro ou timeout de wall. */
  reportOnExit: boolean;
};

export type OperationPauseReason =
  | "llm_exhausted"
  | "step_limit"
  | "llm_error"
  | "operation_wall";

/** @deprecated Legado Vercel/Inngest — não usar como decisor de produto. */
export type LegacyPauseReason = "platform_limit";

export type OperationReportKind = "exit" | "error" | "timeout";

/** Card de report no chat (HOTL) — mesma estrutura visual do task card. */
export type OperationReport = {
  kind: OperationReportKind;
  summary: string;
  steps?: number;
  touchedPaths?: string[];
};

export const COOPERATIVE_WALL_MS = 60 * 60 * 1000;

export const HOTL_WALL_MS: Readonly<Record<HotlWallHours, number>> = {
  24: 24 * 60 * 60 * 1000,
  48: 48 * 60 * 60 * 1000,
  72: 72 * 60 * 60 * 1000,
};

export const DEFAULT_OPERATION_PREFERENCES: OperationPreferences = {
  mode: "cooperative",
};

export function isHotlWallHours(value: unknown): value is HotlWallHours {
  return value === 24 || value === 48 || value === 72;
}

export function isOperationMode(value: unknown): value is OperationMode {
  return value === "cooperative" || value === "hotl";
}

/** Normaliza preferência do perfil ou payload parcial. */
export function parseOperationPreferences(raw: unknown): OperationPreferences {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return { ...DEFAULT_OPERATION_PREFERENCES };
  }
  const r = raw as Record<string, unknown>;
  const mode = isOperationMode(r.mode) ? r.mode : "cooperative";
  const hotlWallHours = isHotlWallHours(r.hotlWallHours) ? r.hotlWallHours : undefined;
  if (mode === "hotl") {
    return { mode, hotlWallHours: hotlWallHours ?? 24 };
  }
  return { mode: "cooperative" };
}

export function resolveOperationWallMs(prefs: OperationPreferences): number {
  if (prefs.mode === "hotl") {
    const hours = prefs.hotlWallHours ?? 24;
    return HOTL_WALL_MS[hours];
  }
  return COOPERATIVE_WALL_MS;
}

/** Cria snapshot imutável no start do dispatch. */
export function snapshotOperation(
  prefs: OperationPreferences,
  startedAt?: string,
): RunOperationMeta {
  const mode = prefs.mode;
  return {
    mode,
    startedAt: startedAt ?? new Date().toISOString(),
    wallMs: resolveOperationWallMs(prefs),
    reportOnExit: mode === "hotl",
  };
}

export function parseRunOperationMeta(raw: unknown): RunOperationMeta | null {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null;
  const r = raw as Record<string, unknown>;
  if (!isOperationMode(r.mode)) return null;
  const startedAt = typeof r.startedAt === "string" ? r.startedAt : null;
  const wallMs = typeof r.wallMs === "number" && r.wallMs > 0 ? r.wallMs : null;
  if (!startedAt || wallMs === null) return null;
  return {
    mode: r.mode,
    startedAt,
    wallMs,
    reportOnExit: r.reportOnExit === true || r.mode === "hotl",
  };
}

export function operationWallExceeded(
  snapshot: Pick<RunOperationMeta, "startedAt" | "wallMs">,
  nowMs: number = Date.now(),
): boolean {
  const start = Date.parse(snapshot.startedAt);
  if (!Number.isFinite(start)) return false;
  return nowMs - start >= snapshot.wallMs;
}

export function remainingOperationMs(
  snapshot: Pick<RunOperationMeta, "startedAt" | "wallMs">,
  nowMs: number = Date.now(),
): number {
  const start = Date.parse(snapshot.startedAt);
  if (!Number.isFinite(start)) return snapshot.wallMs;
  return Math.max(0, snapshot.wallMs - (nowMs - start));
}

/**
 * Cooperative: fusíveis internos (LLM, steps, wall) podem pausar → Continuar emergência.
 * HOTL: só o wall pausa; demais falhas viram report no exit (fase UI depois).
 */
export function shouldPauseForReason(
  mode: OperationMode,
  reason: OperationPauseReason,
): boolean {
  if (reason === "operation_wall") return mode === "cooperative";
  return mode === "cooperative";
}

export type OperationReportInput = {
  kind: OperationReportKind;
  summary: string;
  steps?: number;
  touchedPaths?: string[];
  startedAt?: string;
  wallMs?: number;
};

/** Texto plano no chat — sem card, sem componente extra. */
export function formatOperationReportText(input: OperationReportInput): string {
  const status =
    input.kind === "exit" ? "Concluído" : input.kind === "error" ? "Erro" : "Timeout";
  const wallHours =
    typeof input.wallMs === "number" && input.wallMs > 0
      ? Math.round(input.wallMs / 3_600_000)
      : null;
  const lines = [
    "Relatório (Human on the Loop)",
    `Status: ${status}`,
  ];
  if (wallHours) lines.push(`Wall: ${wallHours}h`);
  if (typeof input.steps === "number") lines.push(`Passos: ${input.steps}`);
  const paths = input.touchedPaths?.filter(Boolean) ?? [];
  if (paths.length > 0) {
    const shown = paths.slice(0, 8);
    const extra = paths.length > 8 ? ` (+${paths.length - 8})` : "";
    lines.push(`Arquivos: ${shown.join(", ")}${extra}`);
  }
  const summary = input.summary.trim();
  if (summary) lines.push(`Resumo: ${summary.slice(0, 600)}`);
  return lines.join("\n");
}

export function withHotlReport(
  closing: string,
  meta: RunOperationMeta,
  ctx: Omit<OperationReportInput, "startedAt" | "wallMs">,
): string {
  if (!meta.reportOnExit) return closing;
  const report = formatOperationReportText({
    ...ctx,
    startedAt: meta.startedAt,
    wallMs: meta.wallMs,
  });
  const base = closing.trim();
  return base ? `${base}\n\n${report}` : report;
}