// AUTO-GENERATED by scripts/sync-agent-contract.mjs — do not edit.
// agent-contract-events — Contrato canônico de eventos do stream do agente.
//
// SSOT: packages/agent-contract/src/events.ts
// SYNC: npm run sync:agent-contract → supabase/functions/agent-run/_events.ts
// FRONTEND: src/lib/agent-event-contract.ts re-exporta este pacote.

// ─── Status canônicos do agent_runs (DB) ───────────────────────────────────
export type AgentRunStatus =
  | "pending"
  | "running"
  | "awaiting_user"
  | "completed"
  | "failed"
  | "canceled";

// ─── Tipos compartilhados ──────────────────────────────────────────────────
export interface PlanStepPayload {
  id: string;
  type: "create_file" | "edit_file" | "shell_exec" | "install_dep" | "observe" | "custom";
  description: string;
  filePath?: string;
  estimatedCost?: number;
  enabled: boolean;
}

export interface DesignReferencePayload {
  url: string;
  title?: string;
  screenshot_url?: string;
  extracted_dna?: string;
}

export interface DesignPlanFieldPayload {
  voice: string[];
  moment: string;
  techniques: string[];
  mood?: string;
  references?: DesignReferencePayload[];
  anti_patterns?: string[];
  synthesis_reasoning?: string;
  auto_check?: { id: string; answer: string; pass: boolean }[];
  relevant_dnas?: string[];
  compositions?: string[];
  composition_exports?: string[];
  read_paths?: string[];
}

// ─── Discriminated union de eventos de stream ──────────────────────────────
//
// Cada variante carrega APENAS o payload de `data`. O envelope
// `{ type, data, timestamp }` é definido separadamente em `AgentStreamEvent`.
//
// Convenção: campos marcados `?` são opcionais no emissor; o consumidor deve
// tolerar a ausência. Campos obrigatórios são exigidos pelo reducer e pelo
// typecheck do emissor.

export type AgentStreamEventData =
  | { type: "start"; provider?: string; taste?: boolean; sessionKind?: string }
  | { type: "canceled"; message: string }
  | {
      type: "assistant_text";
      text: string;
      append?: boolean;
      delta?: boolean;
      opening?: boolean;
      narration?: boolean;
      thinking?: boolean;
      final?: boolean;
    }
  | { type: "thinking_text"; text: string; append?: boolean; delta?: boolean }
  | {
      type: "phase";
      phase: string;
      message?: string;
      task_title?: string;
      toolCount?: number;
      intent?: string;
      task_phase?: string;
    }
  | { type: "explore"; message?: string; paths?: string[] }
  | {
      type: "step_result";
      summary?: string;
      evidence?: string[];
      ok?: boolean;
    }
  | { type: "step"; current: number; total: number; plan?: boolean }
  | {
      type: "context_pressure";
      message?: string;
    }
  | {
      type: "context_compress";
      message?: string;
    }
  | { type: "rate_limit"; message?: string }
  | { type: "robin_rotate"; message?: string }
  | { type: "robin_wait"; message?: string }
  | { type: "connection_retry"; message?: string }
  | { type: "heartbeat"; message?: string; silentMs?: number }
  | { type: "timeout_warning"; message?: string; silentMs?: number }
  | { type: "build_log"; command: string; lines?: string[]; output?: string; ok?: boolean }
  | {
      type: "stack_fork_suggested";
      path: string;
      suggestedStack: string;
      message: string;
    }
  | {
      type: "delivery_checkpoint";
      narration?: string;
      deliveryFiles?: string[];
      silent?: boolean;
      step?: number;
      totalSteps?: number;
      resumable?: boolean;
      message?: string;
    }
  | {
      type: "classify";
      model?: string;
      complexity?: string;
      summary?: string;
      restored?: boolean;
    }
  | {
      type: "skills";
      active?: string[];
      stack?: string[];
      user?: string[];
      invoked?: string[];
    }
  | {
      type: "tool_start";
      name: string;
      args: Record<string, unknown>;
      toolCallId?: string;
      step_intent?: string;
      task_phase?: string;
      file_paths?: string[];
    }
  | {
      type: "tool_done";
      name: string;
      ok: boolean;
      error?: string;
      output?: string;
      summary?: string;
      toolCallId?: string;
    }
  | {
      type: "file_diff";
      path: string;
      before: string;
      after: string;
      op: "write" | "edit";
    }
  | { type: "preview_sync" }
  | { type: "validate_ok"; checks?: Array<{ name: string; ok: boolean }>; message?: string }
  | {
      type: "validate_fail";
      checks?: Array<{ name: string; ok: boolean }>;
      message?: string;
      feedback?: string;
      preflight?: boolean;
      finalGate?: boolean;
      errors?: unknown;
    }
  | { type: "gate_decision"; awaiting: boolean; phase?: string; reason?: string }
  | {
      type: "done";
      summary?: string;
      totalInputTokens?: number;
      totalOutputTokens?: number;
      totalTokens?: number;
      costUsd?: number;
      conversational?: boolean;
      qualified?: boolean;
      awaiting?: boolean;
      planProposed?: boolean;
      planRejected?: boolean;
      inventory?: boolean;
    }
  | {
      type: "plan_proposed";
      planId: string;
      summary: string;
      rationale?: string;
      markdown?: string;
      mission?: string;
      objective?: string;
      steps: PlanStepPayload[];
      runId: string;
      projectId: string;
      design?: DesignPlanFieldPayload;
      ttlMs?: number;
      proposedAt?: string;
    }
  | { type: "error"; message: string; recoverable?: boolean }
  | {
      type: "finish";
      ok: boolean;
      canceled?: boolean;
      resumable?: boolean;
      error?: string | null;
      awaiting?: boolean;
      qualified?: boolean;
      steps?: number;
      summary?: string | null;
      chunkCap?: boolean;
      resumableExhausted?: boolean;
      resumeAttempts?: number;
      duplicate?: boolean;
      totalInputTokens?: number;
      totalOutputTokens?: number;
      totalTokens?: number;
      costUsd?: number;
    }
  | { type: "ui_action"; action: string; reason?: string; [k: string]: unknown }
  | {
      type: "fsm_transition";
      stateName?: string;
      event?: string;
      ok?: boolean;
      error?: string;
      from?: string;
      to?: string;
    }
  | { type: "stuck"; message?: string; reason?: string }
  | {
      type: "typecheck_fail";
      errors?: unknown;
      files?: string[];
      message?: string;
    }
  | { type: "chunk_resume"; attempt: number; maxAttempts: number; reason?: string };

// ─── Envelope do stream ────────────────────────────────────────────────────
export interface AgentStreamEvent {
  type: AgentStreamEventData["type"];
  data: Extract<AgentStreamEventData, { type: AgentStreamEventData["type"] }>;
  timestamp: number;
}

// ─── Helpers de narrowing (zero runtime) ───────────────────────────────────
export type AgentStreamEventType = AgentStreamEventData["type"];

export type PayloadOf<T extends AgentStreamEventType> = Extract<
  AgentStreamEventData,
  { type: T }
>;

// ─── Lista canônica de tipos (para validação runtime se necessário) ────────
export const AGENT_STREAM_EVENT_TYPES: ReadonlyArray<AgentStreamEventType> = [
  "start",
  "canceled",
  "assistant_text",
  "thinking_text",
  "phase",
  "explore",
  "step_result",
  "step",
  "context_pressure",
  "context_compress",
  "rate_limit",
  "robin_rotate",
  "robin_wait",
  "connection_retry",
  "heartbeat",
  "timeout_warning",
  "build_log",
  "stack_fork_suggested",
  "delivery_checkpoint",
  "classify",
  "skills",
  "tool_start",
  "tool_done",
  "file_diff",
  "preview_sync",
  "validate_ok",
  "validate_fail",
  "gate_decision",
  "done",
  "plan_proposed",
  "error",
  "finish",
  "ui_action",
  "fsm_transition",
  "stuck",
  "typecheck_fail",
  "chunk_resume",
];

// ─── Eventos removidos do contrato (deprecated) ────────────────────────────
// `resume` — sem emissor no backend; handler removido do reducer em Session 2.0.
// `memory` — sem emissor no backend; handler removido do reducer em Session 2.0.
