// AUTO-GENERATED by scripts/sync-agent-contract.mjs — do not edit.
// agent-contract-events — Contrato canônico de eventos do stream do agente.
//
// SSOT: packages/agent-contract/src/events.ts
// SYNC: npm run sync:agent-contract → supabase/functions/agent-run/_events.ts
// FRONTEND: src/lib/agent-event-contract.ts re-exporta este pacote.

// ─── Status canônicos do agent_runs (DB) ───────────────────────────────────
export type AgentRunStatus =
  | "pending"
  | "running"
  | "awaiting_user"
  | "completed"
  | "failed"
  | "canceled";

// ─── Tipos compartilhados ──────────────────────────────────────────────────
export interface PlanStepPayload {
  id: string;
  type: "create_file" | "edit_file" | "shell_exec" | "install_dep" | "observe" | "custom";
  description: string;
  filePath?: string;
  estimatedCost?: number;
  enabled: boolean;
}

export interface DesignReferencePayload {
  url: string;
  title?: string;
  screenshot_url?: string;
  extracted_dna?: string;
}

export interface DesignPlanFieldPayload {
  voice: string[];
  moment: string;
  techniques: string[];
  mood?: string;
  references?: DesignReferencePayload[];
  anti_patterns?: string[];
  synthesis_reasoning?: string;
  auto_check?: { id: string; answer: string; pass: boolean }[];
  relevant_dnas?: string[];
  compositions?: string[];
  composition_exports?: string[];
  read_paths?: string[];
}

// ─── Discriminated union de eventos de stream ──────────────────────────────
//
// Cada variante carrega APENAS o payload de `data`. O envelope
// `{ type, data, timestamp }` é definido separadamente em `AgentStreamEvent`.
//
// Convenção: campos marcados `?` são opcionais no emissor; o consumidor deve
// tolerar a ausência. Campos obrigatórios são exigidos pelo reducer e pelo
// typecheck do emissor.

export type AgentStreamEventData =
  | { type: "start"; provider?: string; taste?: boolean; sessionKind?: string }
  | { type: "canceled"; message: string }
  | {
      type: "assistant_text";
      text: string;
      append?: boolean;
      delta?: boolean;
      opening?: boolean;
      narration?: boolean;
      thinking?: boolean;
      final?: boolean;
    }
  | { type: "thinking_text"; text: string; append?: boolean; delta?: boolean }
  | {
      type: "phase";
      phase: string;
      message?: string;
      task_title?: string;
      toolCount?: number;
      intent?: string;
      task_phase?: string;
    }
  | { type: "explore"; message?: string; paths?: string[] }
  | {
      type: "agent_note";
      text: string;
      /** Título curto opcional — se omitido, o frontend usa "Note". */
      title?: string;
    }
  | {
      type: "alert";
      level: "info" | "warn" | "error";
      message: string;
      /** Identificador do alerta para agrupamento/dedup. */
      alertId?: string;
    }
  | {
      type: "design";
      kind: "resolve" | "dna_ready" | "directive" | "build_step";
      title: string;
      detail?: string;
      references?: string[];
    }
  | {
      type: "step_result";
      summary?: string;
      evidence?: string[];
      ok?: boolean;
    }
  | { type: "step"; current: number; total: number; plan?: boolean }
  | {
      type: "task";
      id: string;
      label: string;
      criteria?: string;
      active?: boolean;
      done?: boolean;
      failed?: boolean;
    }
  | {
      type: "context_usage";
      usageTokens?: number;
      windowTokens?: number;
      percent?: number;
      mode?: "manual" | "auto";
      compacting?: boolean;
      source?: "provider" | "estimate";
    }
  | {
      type: "context_compact_done";
      beforeTokens?: number;
      afterTokens?: number;
      percentBefore?: number;
      percentAfter?: number;
      windowTokens?: number;
    }
  | { type: "rate_limit"; message?: string }
  | { type: "robin_rotate"; message?: string }
  | { type: "robin_wait"; message?: string }
  | { type: "connection_retry"; message?: string }
  | { type: "heartbeat"; message?: string; silentMs?: number }
  | { type: "build_log"; command: string; lines?: string[]; output?: string; ok?: boolean }
  | {
      type: "stack_fork_suggested";
      path: string;
      suggestedStack: string;
      message: string;
    }
  | {
      type: "directive";
      brief: string;
      gesture: string;
      techniques: string[];
    }
  | { type: "run_paused"; reason: string; message: string }
  | {
      type: "skills";
      active?: string[];
      stack?: string[];
      user?: string[];
      invoked?: string[];
    }
  | {
      type: "tool_start";
      name: string;
      args: Record<string, unknown>;
      toolCallId?: string;
      step_intent?: string;
      task_phase?: string;
      file_paths?: string[];
    }
  | {
      type: "tool_done";
      name: string;
      ok: boolean;
      error?: string;
      output?: string;
      summary?: string;
      toolCallId?: string;
    }
  | {
      type: "file_diff";
      path: string;
      before: string;
      after: string;
      op: "write" | "edit";
    }
  | {
      type: "done";
      summary?: string;
      totalInputTokens?: number;
      totalOutputTokens?: number;
      totalTokens?: number;
      costUsd?: number;
      conversational?: boolean;
      qualified?: boolean;
      awaiting?: boolean;
      planProposed?: boolean;
      planRejected?: boolean;
      inventory?: boolean;
    }
  | {
      type: "plan_proposed";
      planId: string;
      summary: string;
      rationale?: string;
      markdown?: string;
      mission?: string;
      objective?: string;
      steps: PlanStepPayload[];
      runId: string;
      projectId: string;
      design?: DesignPlanFieldPayload;
      ttlMs?: number;
      proposedAt?: string;
    }
  | { type: "error"; message: string; recoverable?: boolean }
  | {
      type: "finish";
      ok: boolean;
      canceled?: boolean;
      resumable?: boolean;
      error?: string | null;
      awaiting?: boolean;
      qualified?: boolean;
      steps?: number;
      summary?: string | null;
      duplicate?: boolean;
      totalInputTokens?: number;
      totalOutputTokens?: number;
      totalTokens?: number;
      costUsd?: number;
    }
  | { type: "ui_action"; action: string; reason?: string; [k: string]: unknown }
  | { type: "stuck"; message?: string; reason?: string }
  | {
      type: "typecheck_fail";
      errors?: unknown;
      files?: string[];
      message?: string;
    };

// ─── Envelope do stream ────────────────────────────────────────────────────
export interface AgentStreamEvent {
  type: AgentStreamEventData["type"];
  data: Extract<AgentStreamEventData, { type: AgentStreamEventData["type"] }>;
  timestamp: number;
}

// ─── Helpers de narrowing (zero runtime) ───────────────────────────────────
export type AgentStreamEventType = AgentStreamEventData["type"];

export type PayloadOf<T extends AgentStreamEventType> = Extract<
  AgentStreamEventData,
  { type: T }
>;

// ─── Lista canônica de tipos (para validação runtime se necessário) ────────
export const AGENT_STREAM_EVENT_TYPES: ReadonlyArray<AgentStreamEventType> = [
  "start",
  "canceled",
  "assistant_text",
  "thinking_text",
  "phase",
  "explore",
  "agent_note",
  "alert",
  "design",
  "step_result",
  "step",
  "task",
  "context_usage",
  "context_compact_done",
  "rate_limit",
  "robin_rotate",
  "robin_wait",
  "connection_retry",
  "heartbeat",
  "build_log",
  "stack_fork_suggested",
  "directive",
  "run_paused",
  "skills",
  "tool_start",
  "tool_done",
  "file_diff",
  "done",
  "plan_proposed",
  "error",
  "finish",
  "ui_action",
  "stuck",
  "typecheck_fail",
];

/** Tipos proibidos no stream público (execution sanity v2 §6.2) — não emitir nem reintroduzir. */
export const FORBIDDEN_STREAM_EVENT_TYPES = [
  "gate",
  "preview_sync",
  "validate_fail",
  "validate_ok",
  "timeout_warning",
  "chunk_resume",
  "delivery_checkpoint",
  "delivery_checkpoint_silent",
  "checkpoint_resume",
  "fsm_transition",
  "classify",
  "gate_decision",
] as const;

// ─── Eventos removidos do contrato (deprecated) ────────────────────────────
// `resume` — sem emissor no backend; handler removido do reducer em Session 2.0.
// `memory` — sem emissor no backend; handler removido do reducer em Session 2.0.
// §6.2 execution sanity: timeout_warning, delivery_checkpoint, classify, preview_sync,
// validate_fail/ok, gate_decision, fsm_transition, chunk_resume — ver FORBIDDEN_STREAM_EVENT_TYPES.
