/**
 * Seed inicial de DesignDNAs curados — extraídos de sites premiados
 * e referências de design de alto nível.
 *
 * Cada entrada é um "átomo" de design que o agente pode consultar,
 * combinar e sintetizar. Não é cópia — é DNA extraído.
 */

import type { DesignDNA } from "./types";

export const DESIGN_DNA_SEEDS: DesignDNA[] = [
  {
    id: "elevenlabs-hero-split",
    name: "Eleven Labs Hero Split",
    source_url: "https://elevenlabs.io",
    category: "hero",
    serves_domains: ["AI", "SaaS", "voice tech", "tech product"],
    compatible_languages: ["swiss", "high-tech", "editorial", "minimal"],
    compatible_moods: ["ocean", "mono", "neon"],
    layout: {
      type: "split asymmetric 60/40 — headline crosses fold, proof strip integrated",
      grid_system: "CSS grid 2 col, headline left, visual right",
      whitespace_rhythm: "py-32 hero, py-8 proof strip inline",
      breakpoint_behavior: "split → stack em mobile, headline full-width",
      asymmetry_level: 0.6,
      hierarchy_notes: "Headline gigante domina; subtítulo discreto; CTA pair claro",
    },
    motion: {
      types: ["parallax-depth", "stagger", "reveal"],
      parallax_layers: [0.15, 0.4, 1.0],
      stagger: 0.08,
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      duration: 600,
      scroll_choreography: "3-layer parallax: bg mesh 0.15x, mid visual 0.4x, content 1.0x",
    },
    typography: {
      font_stack: "Inter Variable",
      scale: "clamp(3rem, 8vw, 7rem)",
      weight_hierarchy: [700, 500, 300],
      tracking: "-0.02em",
      line_height: "1.05 headline, 1.6 body",
      variable_font: true,
      notes: "Weight drop 700→300 no subhead cria contraste sem trocar fonte",
    },
    color_application: {
      brand_application: "brand only on CTA + accent underline on headline keyword",
      surface_layering: "bg-dark → surface-1 (nav) → surface-2 (cards) com border 1px white/5%",
      gradient_usage: "radial gradient no bg mesh, não no texto",
      accent_usage: "accent-500 no underline do headline keyword + glow shadow no CTA",
      contrast_strategy: "high contrast mono com brand pop — fundo escuro, texto bright",
    },
    component_patterns: [
      {
        type: "HeroSignature",
        anatomy: ["eyebrow badge", "h1 display headline", "subhead max-w-2xl", "dual CTA", "proof strip inline"],
        behavior: "StaggerContainer na entrada, parallax no bg",
        integration: "Proof strip integrada abaixo do CTA, não separada por seção",
      },
    ],
    interactions: {
      types: ["magnetic"],
      effect_radius: 120,
      hover_feedback: "magnetic pull + scale 1.02 + glow intensify",
      cursor_behavior: "default",
    },
    implementation_notes: "z-index: bg(0) → mesh(1) → content(10) → spotlight(20). Parallax só em transform, nunca em top/left.",
    quality_score: 9.2,
    quality_source: "Awwwards SOTD 2024",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "vercel-edge-hero",
    name: "Vercel Edge Hero",
    source_url: "https://vercel.com",
    category: "hero",
    serves_domains: ["SaaS", "dev tools", "platform", "infrastructure"],
    compatible_languages: ["swiss", "high-tech", "minimal"],
    compatible_moods: ["ocean", "mono", "ember"],
    layout: {
      type: "centered max-w-5xl com conic gradient bg + grid pattern overlay",
      grid_system: "single column centered, grid pattern como textura",
      whitespace_rhythm: "py-32 hero, py-16 features, py-24 CTA",
      breakpoint_behavior: "max-w-5xl → px-4 em mobile",
      asymmetry_level: 0.2,
      hierarchy_notes: "Headline gigante centralizado, subtítulo below, CTA pair",
    },
    motion: {
      types: ["animated-mesh", "reveal", "stagger"],
      stagger: 0.1,
      easing: "cubic-bezier(0.4, 0, 0.2, 1)",
      duration: 500,
      scroll_choreography: "Conic gradient rotaciona lentamente (30s linear infinite)",
    },
    typography: {
      font_stack: "Geist Sans (Vercel custom)",
      scale: "clamp(2.5rem, 6vw, 5.5rem)",
      weight_hierarchy: [600, 400, 300],
      tracking: "-0.03em",
      line_height: "1.0 headline, 1.5 body",
      variable_font: false,
      notes: "Tracking tight (-0.03em) no headline cria densidade premium",
    },
    color_application: {
      brand_application: "brand no gradient conic + CTA + link hover",
      surface_layering: "bg-black → surface-1 (cards) com border white/10%",
      gradient_usage: "conic gradient from-brand via-transparent to-accent, rotating",
      accent_usage: "accent no CTA secondary + icon highlights",
      contrast_strategy: "pure black bg com white text + brand glow",
    },
    component_patterns: [
      {
        type: "HeroSignature",
        anatomy: ["h1 display centered", "subhead max-w-2xl centered", "dual CTA centered", "grid pattern bg"],
        behavior: "fade-in + stagger, conic gradient rotation",
        integration: "Features grid abaixo com cards glassmorphism sobre o gradient",
      },
    ],
    interactions: {
      types: ["hover-lift"],
      hover_feedback: "card lift -4px + border brighten + shadow grow",
    },
    implementation_notes: "Conic gradient via background: conic-gradient(from 0deg, ...). Grid pattern via CSS background-image. Rotate via @keyframes.",
    quality_score: 9.0,
    quality_source: "curadoria interna",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "apple-product-hero-cinematic",
    name: "Apple Product Hero Cinematic",
    source_url: "https://apple.com",
    category: "hero",
    serves_domains: ["product", "premium", "consumer tech", "lifestyle"],
    compatible_languages: ["editorial", "minimal", "high-tech"],
    compatible_moods: ["mono", "sand", "sunset"],
    layout: {
      type: "full-bleed cinematic — product image centered, headline above, minimal text",
      grid_system: "single column, full viewport width",
      whitespace_rhythm: "py-40 hero (generoso), py-20 sections",
      breakpoint_behavior: "full-bleed mantém, texto escala down",
      asymmetry_level: 0.1,
      hierarchy_notes: "Product image é o hero. Headline complementa, não domina.",
    },
    motion: {
      types: ["scroll-triggered", "parallax-depth", "reveal"],
      parallax_layers: [0.3, 0.6, 1.0],
      easing: "cubic-bezier(0.28, 0.11, 0.32, 1)",
      duration: 800,
      scroll_choreography: "Product image parallax sutil, text fade out on scroll, next section fade in",
    },
    typography: {
      font_stack: "SF Pro Display",
      scale: "clamp(2rem, 5vw, 4.5rem)",
      weight_hierarchy: [600, 400],
      tracking: "-0.01em",
      line_height: "1.1 headline",
      variable_font: false,
      notes: "Semibold não bold. Densidade moderada. Respiração máxima.",
    },
    color_application: {
      brand_application: "brand quase ausente — product é a cor",
      surface_layering: "bg-white ou bg-black puro, sem surfaces intermediárias",
      gradient_usage: "subtle radial gradient atrás do product, quase imperceptível",
      contrast_strategy: "monochrome bg + product color pop",
    },
    component_patterns: [
      {
        type: "CinematicHero",
        anatomy: ["headline gigante", "subhead 1 linha", "product image full-bleed", "CTA text link (não button)"],
        behavior: "parallax no product, fade no text",
        integration: "Scroll leva naturalmente à próxima seção sem CTA block",
      },
    ],
    interactions: {
      types: ["scroll-snap"],
      hover_feedback: "CTA text link underline grow",
    },
    implementation_notes: "Product image precisa de mask-image ou clip-path para fade out no scroll. Scroll-snap entre seções.",
    quality_score: 9.8,
    quality_source: "curadoria interna (Apple design benchmark)",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "stripe-editorial-density",
    name: "Stripe Editorial Density",
    source_url: "https://stripe.com",
    category: "layout",
    serves_domains: ["fintech", "SaaS", "payments", "enterprise", "documentation"],
    compatible_languages: ["swiss", "editorial", "high-tech"],
    compatible_moods: ["ocean", "mono", "royal"],
    layout: {
      type: "editorial multi-column com alta densidade de informação",
      grid_system: "12 colunas rígido, conteúdo em 8 col, sidebar/visual em 4 col",
      whitespace_rhythm: "py-24 hero, py-16 dense sections, py-32 breathing",
      breakpoint_behavior: "12 col → 6 col tablet → 1 col mobile",
      asymmetry_level: 0.4,
      hierarchy_notes: "H1 + H2 editorial com serifa display + body sans-serif. Dual-column com visual supporting text.",
    },
    motion: {
      types: ["scroll-reveal", "animated-mesh", "stagger"],
      stagger: 0.12,
      easing: "cubic-bezier(0.4, 0, 0.2, 1)",
      duration: 400,
      scroll_choreography: "Gradient mesh animado no bg, content reveal staggerado por seção",
    },
    typography: {
      font_stack: "Sohne (Stripe custom) / Inter fallback",
      scale: "clamp(2.5rem, 5vw, 4.5rem)",
      weight_hierarchy: [600, 500, 400],
      tracking: "-0.02em",
      line_height: "1.1 headline, 1.6 body",
      variable_font: false,
      notes: "Serifa display opcional no H1 para contraste editorial. Body sans-serif denso.",
    },
    color_application: {
      brand_application: "brand gradient no bg mesh + CTA + accent em links",
      surface_layering: "bg-white → surface-1 (cards) → surface-2 (code blocks) com border subtle",
      gradient_usage: "animated mesh gradient no bg, 6+ cores com blur",
      accent_usage: "accent em code syntax + link hover + icon backgrounds",
      contrast_strategy: "light mode: white bg + colored mesh. dark mode: dark bg + vivid mesh.",
    },
    component_patterns: [
      {
        type: "EditorialHero",
        anatomy: ["h1 display", "subhead 2 lines", "dual CTA", "code/visual right column", "logo strip below"],
        behavior: "mesh bg animation, stagger reveal",
        integration: "Code/visual na coluna direita complementa texto na esquerda",
      },
      {
        type: "FeatureMatrix",
        anatomy: ["icon", "title", "description", "code snippet ou visual"],
        behavior: "reveal on scroll, hover lift",
        integration: "Grid 3-col em desktop, 1-col mobile com visual entre items",
      },
    ],
    interactions: {
      types: ["hover-lift", "spotlight-cursor"],
      hover_feedback: "card lift + border brighten + shadow grow",
      cursor_behavior: "spotlight 400px em seções com visual rico",
    },
    implementation_notes: "Mesh gradient via multiple radial-gradients com animation. Code blocks com syntax highlight.",
    quality_score: 9.5,
    quality_source: "Awwwards SOTD + curadoria interna",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "linear-motion-choreography",
    name: "Linear Motion Choreography",
    source_url: "https://linear.app",
    category: "motion",
    serves_domains: ["SaaS", "dev tools", "project management", "productivity"],
    compatible_languages: ["swiss", "high-tech", "minimal"],
    compatible_moods: ["ocean", "mono", "neon"],
    layout: {
      type: "centered max-w-4xl com visual abaixo do fold",
      grid_system: "single column centered",
      whitespace_rhythm: "py-32 hero, py-20 visual, py-16 features",
      breakpoint_behavior: "centered → left-aligned mobile",
      asymmetry_level: 0.1,
      hierarchy_notes: "Headline + subhead + CTA → visual rico abaixo. Simples mas executado impecavelmente.",
    },
    motion: {
      types: ["scroll-reveal", "stagger", "parallax-depth", "animated-mesh"],
      parallax_layers: [0.2, 0.5, 1.0],
      stagger: 0.06,
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      duration: 500,
      scroll_choreography: "Cada seção revela com stagger. Visual abaixo do fold tem parallax 3-layer. Mesh bg sutil animado.",
    },
    typography: {
      font_stack: "Inter Variable",
      scale: "clamp(2.5rem, 6vw, 5rem)",
      weight_hierarchy: [600, 400, 300],
      tracking: "-0.02em",
      line_height: "1.1 headline, 1.5 body",
      variable_font: true,
      notes: "Inter tight tracking + weight 600 (não bold) = feel tech premium",
    },
    color_application: {
      brand_application: "brand no gradient mesh bg + CTA + accent em tags",
      surface_layering: "bg-dark → surface-1 (nav glass) → surface-2 (cards) com border white/10%",
      gradient_usage: "animated mesh gradient bg, brand + accent cores, blur pesado",
      accent_usage: "accent em feature tags + status indicators",
      contrast_strategy: "dark mode: bg-dark + mesh + white text. Sem light mode.",
    },
    component_patterns: [
      {
        type: "HeroSignature",
        anatomy: ["h1 display", "subhead 1 line", "dual CTA", "mesh bg"],
        behavior: "stagger reveal + mesh animation",
        integration: "Product screenshot abaixo com parallax reveal",
      },
    ],
    interactions: {
      types: ["magnetic", "hover-lift"],
      effect_radius: 100,
      hover_feedback: "magnetic pull leve + card lift + border brighten",
    },
    implementation_notes: "Mesh gradient: 4 radial-gradients com animation delay escalonada. Parallax só em transform/y.",
    quality_score: 9.3,
    quality_source: "Awwwards SOTD + FWA",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "awwwards-brutalist-typography",
    name: "Awwwards Brutalist Typography Hero",
    source_url: "https://www.awwwards.com/sites-of-the-day/",
    category: "hero",
    serves_domains: ["creative agency", "studio", "portfolio", "art", "fashion", "artisanal"],
    compatible_languages: ["brutalist", "editorial", "swiss"],
    compatible_moods: ["mono", "sand", "ember"],
    layout: {
      type: "full-bleed typographic — headline gigante ocupa viewport inteiro",
      grid_system: "CSS grid 1 col, full viewport, type as layout",
      whitespace_rhythm: "py-0 (full viewport), px-8, type escala para preencher",
      breakpoint_behavior: "type escala down com clamp, mantém full-bleed",
      asymmetry_level: 0.3,
      hierarchy_notes: "Type IS the design. Sem imagem, sem card, sem decoração. Apenas tipografia gigante.",
    },
    motion: {
      types: ["kinetic-typography", "grain-texture-overlay"],
      stagger: 0.15,
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      duration: 1000,
      scroll_choreography: "Letras revelam por máscara, escalonadas. Grain texture sutil overlay em tudo.",
    },
    typography: {
      font_stack: "grotesk display (Helvetica, Neue Haas, ou similar)",
      scale: "clamp(4rem, 15vw, 14rem)",
      weight_hierarchy: [700, 400],
      tracking: "-0.04em",
      line_height: "0.9 headline",
      variable_font: false,
      notes: "Tracking extremo (-0.04em) + line-height 0.9 = densidade brutalist. Letters overlap intentionally.",
    },
    color_application: {
      brand_application: "brand quase ausente — mono dominante, accent em 1 detalhe",
      surface_layering: "bg-white ou bg-black puro, sem surfaces",
      gradient_usage: "nenhum gradient — cor chapada",
      accent_usage: "accent em 1 palavra ou 1 elemento apenas (underline, box, slash)",
      contrast_strategy: "pure mono (black on white ou white on black) + 1 accent pop",
    },
    component_patterns: [
      {
        type: "BrutalistTypographicHero",
        anatomy: ["headline gigante full-bleed", "subhead pequeno discreto", "CTA minimal text link"],
        behavior: "kinetic reveal por letra, grain overlay",
        integration: "Próxima seção entra com scroll-snap, mantém full-bleed",
      },
    ],
    interactions: {
      types: ["cursor-follow"],
      hover_feedback: "text color invert on hover (black↔white)",
      cursor_behavior: "custom cursor: circle outline que segue com lag",
    },
    implementation_notes: "Headline com mask-image reveal por letra. Grain via SVG noise filter overlay opacity 0.03.",
    quality_score: 9.0,
    quality_source: "Awwwards SOTD curadoria",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "editorial-magazine-split",
    name: "Editorial Magazine Split Layout",
    source_url: "https://www.vogue.com",
    category: "layout",
    serves_domains: ["fashion", "lifestyle", "magazine", "editorial", "luxury", "beauty"],
    compatible_languages: ["editorial", "art-deco", "minimal"],
    compatible_moods: ["mono", "sunset", "royal", "sand"],
    layout: {
      type: "editorial split assimétrico — visual grande à direita, texto coluna estreita à esquerda",
      grid_system: "CSS grid 3+9 col (texto 3, visual 9) ou 4+8",
      whitespace_rhythm: "py-32 hero, py-24 editorial sections, generous line-height",
      breakpoint_behavior: "split → stack mobile, visual first",
      asymmetry_level: 0.7,
      hierarchy_notes: "Visual domina. Texto é complementar, em coluna estreita com serifa.",
    },
    motion: {
      types: ["scroll-reveal", "parallax-depth"],
      parallax_layers: [0.3, 0.7, 1.0],
      easing: "cubic-bezier(0.28, 0.11, 0.32, 1)",
      duration: 700,
      scroll_choreography: "Visual parallax sutil, texto fade in. Scroll reveals próxima story.",
    },
    typography: {
      font_stack: "serif display (Playfair, Bodoni, ou similar) + sans-serif body",
      scale: "clamp(2rem, 4vw, 4rem)",
      weight_hierarchy: [400, 300],
      tracking: "0em headline (serif), 0.01em body",
      line_height: "1.2 headline, 1.8 body",
      variable_font: false,
      notes: "Serif display weight 400 (não bold) = elegância editorial. Body sans-serif light com line-height generoso.",
    },
    color_application: {
      brand_application: "brand ausente — cor vem do visual fotográfico",
      surface_layering: "bg-white puro, sem surfaces",
      gradient_usage: "nenhum — fotografia é a cor",
      accent_usage: "accent em 1 detalhe (line, tag, caption)",
      contrast_strategy: "white bg + photo color + black text",
    },
    component_patterns: [
      {
        type: "EditorialSplit",
        anatomy: ["serif h1 narrow column", "subhead italic", "visual full-height right", "caption small"],
        behavior: "parallax no visual, fade no texto",
        integration: "Próxima seção: outra story com split invertido (texto direita, visual esquerda) — ritmo",
      },
    ],
    interactions: {
      types: ["hover-zoom"],
      hover_feedback: "visual scale 1.02 + cursor → pointer",
    },
    implementation_notes: "Grid 3+9 com gap-0 (visual colado). Serif via Google Fonts ou local. Parallax só no visual.",
    quality_score: 8.8,
    quality_source: "curadoria interna (editorial benchmark)",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "bento-dense-showcase",
    name: "Bento Dense Showcase",
    source_url: "https://www.gumroad.com",
    category: "component_pattern",
    serves_domains: ["SaaS", "product", "marketplace", "creator tools", "portfolio"],
    compatible_languages: ["swiss", "high-tech", "minimal"],
    compatible_moods: ["ocean", "mono", "ember", "sand"],
    layout: {
      type: "bento grid denso — cards de tamanhos variados organizados em grid assimétrico",
      grid_system: "CSS grid 4 col, cards span 1-3 cols e 1-2 rows",
      whitespace_rhythm: "py-24 bento, gap-4 entre cards",
      breakpoint_behavior: "4 col → 2 col tablet → 1 col mobile",
      asymmetry_level: 0.5,
      hierarchy_notes: "Card maior (span 2x2) é o destaque. Cards menores agrupam features secundárias.",
    },
    motion: {
      types: ["stagger", "reveal", "spotlight-cursor"],
      stagger: 0.08,
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      duration: 400,
      scroll_choreography: "Cards revelam em cascade pelo grid. Spotlight segue cursor dentro do bento.",
    },
    typography: {
      font_stack: "Inter Variable",
      scale: "clamp(1.5rem, 3vw, 2.5rem) card titles",
      weight_hierarchy: [600, 400],
      tracking: "-0.02em",
      line_height: "1.2 card title, 1.5 body",
      variable_font: true,
    },
    color_application: {
      brand_application: "brand no card destaque + CTA dentro de cards",
      surface_layering: "bg-dark → surface-1 (cards) → surface-2 (card destaque) com border white/10%",
      gradient_usage: "gradient sutil no card destaque (from-brand/10 to-transparent)",
      accent_usage: "accent em icons + tags dentro de cards",
      contrast_strategy: "dark bg + cards surface + 1 card destaque com gradient brand",
    },
    component_patterns: [
      {
        type: "BentoGrid",
        anatomy: ["card destaque (span 2x2)", "feature cards (span 1x1)", "wide cards (span 2x1)", "tall cards (span 1x2)"],
        behavior: "stagger reveal + spotlight cursor + hover lift",
        integration: "Bento substitui features grid tradicional. Mais denso, mais visual, mais premium.",
      },
    ],
    interactions: {
      types: ["spotlight-cursor", "hover-lift"],
      effect_radius: 300,
      hover_feedback: "card lift -2px + border brighten + spotlight glow",
      cursor_behavior: "spotlight radial gradient segue cursor dentro do bento",
    },
    implementation_notes: "Grid: grid-cols-4 auto-rows-[200px]. Cards: col-span-2 row-span-2 para destaque.",
    quality_score: 8.9,
    quality_source: "curadoria interna (bento trend 2024-2025)",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "sticky-stack-narrative",
    name: "Sticky Stack Narrative",
    source_url: "https://www.apple.com/iphone",
    category: "component_pattern",
    serves_domains: ["product", "storytelling", "showcase", "portfolio", "feature deep-dive"],
    compatible_languages: ["editorial", "minimal", "swiss", "high-tech"],
    compatible_moods: ["mono", "ocean", "sand", "ember"],
    layout: {
      type: "sticky scroll storytelling — seção fixa enquanto conteúdo rola ao lado",
      grid_system: "CSS grid 2 col: col esquerda sticky, col direita scroll content",
      whitespace_rhythm: "py-0 sticky (100vh), col direita py-20 por item",
      breakpoint_behavior: "sticky → stack mobile (col esquerda vira header)",
      asymmetry_level: 0.6,
      hierarchy_notes: "Col esquerda: título + descrição fixos. Col direita: 3-5 items que scroll.",
    },
    motion: {
      types: ["sticky-stack", "scroll-reveal", "parallax-depth"],
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      duration: 400,
      scroll_choreography: "Col esquerda sticky. Col direita items revelam um a um no scroll. Parallax sutil no visual.",
    },
    typography: {
      font_stack: "Inter Variable ou SF Pro",
      scale: "clamp(2rem, 4vw, 3.5rem) sticky title",
      weight_hierarchy: [600, 400],
      tracking: "-0.02em",
      line_height: "1.2 title, 1.6 body",
      variable_font: true,
    },
    color_application: {
      brand_application: "brand no sticky title + accent nos items",
      surface_layering: "bg-dark → surface-1 (items) com border subtle",
      gradient_usage: "gradient sutil de transição entre items (from-transparent via-brand/5 to-transparent)",
      accent_usage: "accent em item number + icon",
      contrast_strategy: "dark bg + items surface + sticky title bright",
    },
    component_patterns: [
      {
        type: "StickyStack",
        anatomy: ["sticky col (title + description)", "scroll col (3-5 items com visual + text)"],
        behavior: "sticky position + reveal staggerado",
        integration: "Substitui features tradicionais. Melhor para deep-dive de produto ou storytelling.",
      },
    ],
    interactions: {
      types: ["hover-lift"],
      hover_feedback: "item card lift + border brighten",
    },
    implementation_notes: "Sticky: position: sticky; top: 0; height: 100vh na col esquerda. Scroll col normal.",
    quality_score: 9.1,
    quality_source: "curadoria interna (Apple pattern)",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "spotlight-showcase-portfolio",
    name: "Spotlight Showcase Portfolio",
    source_url: "https://www.rauno.me",
    category: "interaction",
    serves_domains: ["portfolio", "studio", "creative", "designer", "agency"],
    compatible_languages: ["swiss", "minimal", "editorial"],
    compatible_moods: ["mono", "ocean", "ember"],
    layout: {
      type: "minimal grid com spotlight interativo — cards simples que ganham vida no hover",
      grid_system: "CSS grid 2-3 col, cards uniformes",
      whitespace_rhythm: "py-32 hero, py-16 showcase grid, py-24 footer",
      breakpoint_behavior: "3 col → 2 col → 1 col",
      asymmetry_level: 0.2,
      hierarchy_notes: "Simplicidade extrema. O spotlight é o diferencial — não a estrutura.",
    },
    motion: {
      types: ["spotlight-cursor", "reveal", "stagger"],
      stagger: 0.1,
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      duration: 300,
      scroll_choreography: "Cards revelam staggerado. Spotlight segue cursor com lag suave.",
    },
    typography: {
      font_stack: "Inter Variable",
      scale: "clamp(2rem, 5vw, 4rem)",
      weight_hierarchy: [600, 400],
      tracking: "-0.02em",
      line_height: "1.1 headline, 1.5 body",
      variable_font: true,
      notes: "Minimal typography — o spotlight faz o trabalho visual, não a type.",
    },
    color_application: {
      brand_application: "brand no spotlight glow + CTA",
      surface_layering: "bg-dark → surface-1 (cards) com border white/5%",
      gradient_usage: "radial gradient no spotlight (from-brand/20 to-transparent)",
      accent_usage: "accent em spotlight secundário + link hover",
      contrast_strategy: "dark bg + cards subtle + spotlight pop",
    },
    component_patterns: [
      {
        type: "SpotlightGrid",
        anatomy: ["minimal cards", "spotlight overlay", "icon ou visual pequeno", "title + 1 line desc"],
        behavior: "spotlight segue cursor, card brighten on hover",
        integration: "Grid de showcase onde cada card é um projeto/item. Spotlight cria profundidade.",
      },
    ],
    interactions: {
      types: ["spotlight-cursor"],
      effect_radius: 400,
      hover_feedback: "card brighten + spotlight intensify + border appear",
      cursor_behavior: "spotlight radial gradient segue cursor com lag 0.1s",
    },
    implementation_notes: "Spotlight: div absolute com radial-gradient, position via mousemove, transition transform 0.1s.",
    quality_score: 9.4,
    quality_source: "Awwwards SOTD + curadoria interna (Rauno benchmark)",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "kinetic-headline-reveal",
    name: "Kinetic Headline Reveal",
    source_url: "https://archive.awwwards.com",
    category: "motion",
    serves_domains: ["brand", "manifesto", "about", "agency", "studio", "launch"],
    compatible_languages: ["brutalist", "editorial", "swiss", "bauhaus"],
    compatible_moods: ["mono", "ember", "sunset", "neon"],
    layout: {
      type: "centered ou split com headline como protagonista absoluto",
      grid_system: "single column centered ou split 50/50",
      whitespace_rhythm: "py-40 hero (generoso, deixa a type respirar)",
      breakpoint_behavior: "type escala down, mantém protagonismo",
      asymmetry_level: 0.2,
      hierarchy_notes: "Headline é 80% do impacto. Resto é silêncio.",
    },
    motion: {
      types: ["kinetic-typography", "grain-texture-overlay", "reveal"],
      stagger: 0.12,
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      duration: 1200,
      scroll_choreography: "Letras/palavras revelam por máscara, escalonadas. Grain sobre tudo. Scroll = próxima reveal.",
    },
    typography: {
      font_stack: "display grotesk ou serif (projeto-dependente)",
      scale: "clamp(3rem, 10vw, 9rem)",
      weight_hierarchy: [700, 400],
      tracking: "-0.03em",
      line_height: "0.95 headline",
      variable_font: false,
      notes: "Scale extremo + tracking tight + line-height baixo = densidade cinematográfica",
    },
    color_application: {
      brand_application: "brand em 1 palavra ou accent only",
      surface_layering: "bg puro (white ou black), sem surfaces",
      gradient_usage: "nenhum — type é o visual",
      accent_usage: "accent em 1 detalhe: underline, slash, ou box em 1 palavra",
      contrast_strategy: "mono puro + 1 accent",
    },
    component_patterns: [
      {
        type: "KineticHero",
        anatomy: ["headline gigante", "subhead discreto", "CTA text link minimal"],
        behavior: "mask-image reveal por palavra, grain overlay",
        integration: "Próxima seção: split ou bento para contraste com o hero tipográfico",
      },
    ],
    interactions: {
      types: ["cursor-follow"],
      hover_feedback: "CTA underline grow + color shift",
      cursor_behavior: "custom cursor: small dot + outline ring com lag",
    },
    implementation_notes: "Mask reveal: cada palavra em span com overflow hidden, inner translateY 100%→0 com stagger.",
    quality_score: 9.2,
    quality_source: "Awwwards SOTD curadoria",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "glassmorphism-nav-floating",
    name: "Glassmorphism Floating Nav",
    source_url: "https://linear.app",
    category: "navigation",
    serves_domains: ["SaaS", "product", "portfolio", "agency", "tech"],
    compatible_languages: ["swiss", "high-tech", "minimal", "editorial"],
    compatible_moods: ["ocean", "mono", "neon", "ember"],
    layout: {
      type: "nav flutuante com glassmorphism — sticky top-4, rounded-2xl, backdrop-blur",
      grid_system: "nav inline-flex, max-w-5xl, centered",
      whitespace_rhythm: "nav top-4, py-3 internal, content py-32 below",
      breakpoint_behavior: "nav → hamburger mobile, mantém glass",
      asymmetry_level: 0.0,
      hierarchy_notes: "Nav discreta mas presente. Glass cria profundidade sem bloquear conteúdo.",
    },
    motion: {
      types: ["reveal"],
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      duration: 300,
      scroll_choreography: "Nav fade in on load. Em scroll down, nav pode hide; em scroll up, nav show.",
    },
    typography: {
      font_stack: "Inter Variable",
      scale: "0.875rem nav links",
      weight_hierarchy: [500],
      tracking: "0em",
      line_height: "1.0 nav",
      variable_font: true,
      notes: "Nav font menor que body. Peso medium. Hover: color shift + underline subtle.",
    },
    color_application: {
      brand_application: "brand no logo + CTA na nav",
      surface_layering: "nav: bg-surface-1/60 backdrop-blur-xl border-white/10",
      gradient_usage: "nenhum na nav",
      accent_usage: "accent no active link + CTA hover",
      contrast_strategy: "glass: semi-transparente sobre conteúdo. Texto bright para legibilidade.",
    },
    component_patterns: [
      {
        type: "NavShell",
        anatomy: ["logo left", "links center", "CTA right", "glass container rounded-2xl"],
        behavior: "sticky top-4, backdrop-blur, border subtle",
        integration: "Flutua sobre o hero. Glass funciona SÓ sobre mesh/parallax/gradient bg.",
      },
    ],
    interactions: {
      types: ["hover-color-shift"],
      hover_feedback: "link color shift para brand + underline grow",
    },
    implementation_notes: "CRÍTICO: glass só funciona sobre conteúdo animado (mesh/parallax). Sobre bg chapado, glass é invisível.",
    quality_score: 8.7,
    quality_source: "curadoria interna (Linear pattern)",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "grain-texture-artisanal",
    name: "Grain Texture Artisanal",
    source_url: "https://www.instagram.com/explore/tags/brutalistweb",
    category: "component_pattern",
    serves_domains: ["artisanal", "craft", "food", "bakery", "coffee", "handmade", "fashion"],
    compatible_languages: ["brutalist", "editorial", "japanese-minimalism", "scandinavian"],
    compatible_moods: ["sand", "mono", "ember", "forest"],
    layout: {
      type: "qualquer — grain é overlay, não estrutura",
      grid_system: "independente de grid",
      whitespace_rhythm: "independente",
      breakpoint_behavior: "grain escala com viewport",
      asymmetry_level: 0,
      hierarchy_notes: "Grain adiciona textura tátil — sensação de papel/material real",
    },
    motion: {
      types: ["grain-texture-overlay"],
      easing: "linear",
      duration: 0,
      scroll_choreography: "Grain estático ou com movimento sutil (opacity flicker 0.03→0.05)",
    },
    typography: {
      font_stack: "qualquer — grain complementa, não dita",
      scale: "qualquer",
      weight_hierarchy: [400],
      variable_font: false,
      notes: "Grain funciona melhor com serif ou grotesk — tipografia com personalidade",
    },
    color_application: {
      brand_application: "independente — grain afeta tudo igualmente",
      surface_layering: "grain sobre TUDO: bg, surfaces, cards, imagens",
      gradient_usage: "grain sobre gradient = profundidade adicional",
      contrast_strategy: "grain reduz contraste ligeiramente — compensar com texto slightly brighter",
    },
    component_patterns: [
      {
        type: "GrainOverlay",
        anatomy: ["div absolute inset-0 pointer-events-none", "SVG noise filter ou PNG noise", "opacity 0.03-0.05", "mix-blend-mode overlay"],
        behavior: "estático ou flicker sutil",
        integration: "Última camada acima de tudo. z-index máximo. pointer-events-none.",
      },
    ],
    interactions: {},
    implementation_notes: "SVG: <filter><feTurbulence type='fractalNoise' baseFrequency='0.9'/></filter>. Ou PNG noise tile 200x200, repeat.",
    quality_score: 8.5,
    quality_source: "curadoria interna (texture trend 2024-2025)",
    extracted_at: "2025-06-01",
    validated: true,
  },
  {
    id: "parallax-depth-3layer",
    name: "Parallax Depth 3-Layer",
    source_url: "https://spacedesignify.com",
    category: "motion",
    serves_domains: ["product", "showcase", "storytelling", "hero", "premium"],
    compatible_languages: ["swiss", "editorial", "high-tech", "minimal"],
    compatible_moods: ["ocean", "mono", "ember", "neon", "sand"],
    layout: {
      type: "independente — parallax é técnica de motion, não estrutura",
      grid_system: "qualquer",
      whitespace_rhythm: "qualquer",
      breakpoint_behavior: "parallax desabilita em mobile (performance + nausea)",
      asymmetry_level: 0,
      hierarchy_notes: "Parallax cria profundidade entre camadas — bg, mid, fg",
    },
    motion: {
      types: ["parallax-depth"],
      parallax_layers: [0.2, 0.5, 1.0],
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      duration: 0,
      scroll_choreography: "3 camadas: bg (0.2x scroll speed), mid (0.5x), fg (1.0x). Diferença cria ilusão de profundidade.",
    },
    typography: {},
    color_application: {},
    component_patterns: [
      {
        type: "ParallaxLayer",
        anatomy: ["bg layer (mesh, gradient, ou visual)", "mid layer (visual secundário)", "fg layer (content)"],
        behavior: "translateY baseado em scrollY * speed factor",
        integration: "Usar em hero, showcase, ou seção inteira. Max 3 camadas para performance.",
      },
    ],
    interactions: {},
    implementation_notes: "Transform translateY only. will-change: transform. prefers-reduced-motion: desabilitar. Max 3 camadas para 60fps.",
    quality_score: 8.8,
    quality_source: "curadoria interna (parallax best practice)",
    extracted_at: "2025-06-01",
    validated: true,
  },
];
