// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseEnv } from "@/lib/supabase-env";

export const SUPABASE_NOT_CONFIGURED =
  "Supabase não está configurado. Adicione VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no deploy.";

function createSupabaseClient(): SupabaseClient<Database> {
  const { url, publishableKey, isConfigured } = getSupabaseEnv();

  if (!isConfigured) {
    console.error(`[Supabase] ${SUPABASE_NOT_CONFIGURED}`);
    // Placeholder client — auth returns empty session; data calls surface a clear error.
    return createClient<Database>("https://placeholder.supabase.co", "placeholder-key", {
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  }

  return createClient<Database>(url!, publishableKey!, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: SupabaseClient<Database> | undefined;

export function isSupabaseConfigured(): boolean {
  return getSupabaseEnv().isConfigured;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});